### ISSUE TITLE
Shadow in small charts with background-color white

### ISSUE THREAD

**Issue by ffuentes** [pablomolnar/radial-progress-chart#1]
Hi,
I found your chart very good but have an issue when the container has white background. As you can check in your webpage changing the background color on week activity demo, we can see a lot of shadow. That doesn't seems to bother in big charts, but in small ones is annoying. Do you know how can I fix? Maybe in the configuration would be possible to set the shadow width?

Thanks,
Felipe.

**Comment by pablomolnar** [comment]
Check version v0.0.3 and updated documentation. Added shadow width property in the options object:

```
shadow: {
    width: int (default: 4)
 }
```
